In [111]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')

In [112]:
dataset = pd.read_csv('bankloans.csv')

In [113]:
dataset.head()

Yash  Tehsil  Ish Tecrubesi  Gelir  Gelirxerc nisbeti  Kredit borcu  \
0    41       3             17    176                9.3         11.36   
1    27       1             10     31               17.3          1.36   
2    40       1             15     55                5.5          0.86   
3    41       1             15    120                2.9          2.66   
4    24       2              2     28               17.3          1.79   

   Diger borc  Gecikme  
0        5.01        1  
1        4.00        0  
2        2.17        0  
3        0.82        0  
4        3.06        1

In [114]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1150 entries, 0 to 1149
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Yash               1150 non-null   int64  
 1   Tehsil             1150 non-null   int64  
 2   Ish Tecrubesi      1150 non-null   int64  
 3   Gelir              1150 non-null   int64  
 4   Gelirxerc nisbeti  1150 non-null   float64
 5   Kredit borcu       1150 non-null   float64
 6   Diger borc         1150 non-null   float64
 7   Gecikme            1150 non-null   int64  
dtypes: float64(3), int64(5)
memory usage: 72.0 KB


In [115]:
print(dataset.isnull().sum())

Yash                 0
Tehsil               0
Ish Tecrubesi        0
Gelir                0
Gelirxerc nisbeti    0
Kredit borcu         0
Diger borc           0
Gecikme              0
dtype: int64


In [116]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [117]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , train_size = 0.2 , random_state = 9 )

In [118]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [207]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def model_train(model):
    model.fit(x_train, y_train)
    
    y_pred = model.predict(x_test)

    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    y_test_reshaped = y_test.reshape(-1, 1)
    y_pred_reshaped = y_pred.reshape(-1, 1)
    
    print(f"Accuracy: {accuracy:.2f}, Precision: {precision:.2f}, Recall: {recall:.2f}, F1 Score: {f1:.2f}")
    result = np.concatenate((y_test_reshaped, y_pred_reshaped), axis=1)
    print(result)
    return accuracy, precision, recall, f1


In [209]:
from sklearn.linear_model import LogisticRegression
model_logistic = LogisticRegression()

In [211]:
model_train(model_logistic)

Accuracy: 0.83, Precision: 0.49, Recall: 0.16, F1 Score: 0.25
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


(0.8326086956521739,
 0.49019607843137253,
 0.16339869281045752,
 0.24509803921568626)

In [213]:
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()

In [215]:
model_train(model_tree)

Accuracy: 0.81, Precision: 0.41, Recall: 0.33, F1 Score: 0.36
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


(0.808695652173913,
 0.4065040650406504,
 0.32679738562091504,
 0.36231884057971014)

In [217]:
from sklearn.ensemble import RandomForestClassifier
model_forest = RandomForestClassifier()

In [219]:
model_train(model_forest)

Accuracy: 0.84, Precision: 0.52, Recall: 0.15, F1 Score: 0.23
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


(0.8358695652173913, 0.5227272727272727, 0.1503267973856209, 0.233502538071066)